/**
 * Feature Exporter for Low-Code Builder V2
 * Generates all files for a complete feature folder structure
 *
 * Requirements: 4.1, 4.2, 4.3, 4.4, 4.5, 6.1, 6.2
 */

import type { EntityDefinition } from "../types/entityDefinition";
import { generateInterface, generateZodSchema } from "./codeGenerator";
import {
  generateFormComponent,
  generateCardComponent,
  generateListComponent,
} from "./componentGenerator";
import {
  generateListPage,
  generateCreatePage,
  generateEditPage,
} from "./pageGenerator";
import { generateService } from "./serviceGenerator";

/**
 * Represents a generated file with its path and content
 */
export interface GeneratedFile {
  path: string;
  content: string;
}

/**
 * Result of an export operation
 */
export interface ExportResult {
  success: boolean;
  files: string[];
  error?: string;
}

/**
 * Converts entity name to lowercase for file/variable names
 */
function toLowerCamelCase(name: string): string {
  return name.charAt(0).toLowerCase() + name.slice(1);
}

/**
 * Generates the types file content (interface + schema)
 */
function generateTypesFile(entity: EntityDefinition): string {
  const interfaceCode = generateInterface(entity);
  const schemaCode = generateZodSchema(entity);

  return `/**
 * ${entity.name} Types
 * Auto-generated by Low-Code Builder
 */

import { z } from "zod";

${interfaceCode}

${schemaCode}

export type ${entity.name}Input = Omit<${entity.name}, "id">;
`;
}

/**
 * Generates component index file with all exports
 */
function generateComponentsIndex(entityName: string): string {
  return `/**
 * ${entityName} Components
 * Auto-generated by Low-Code Builder
 */

export { ${entityName}Form } from "./${entityName}Form";
export { ${entityName}Card } from "./${entityName}Card";
export { ${entityName}List } from "./${entityName}List";
`;
}

/**
 * Generates pages index file with all exports
 */
function generatePagesIndex(entityName: string): string {
  return `/**
 * ${entityName} Pages
 * Auto-generated by Low-Code Builder
 */

export { ${entityName}ListPage } from "./${entityName}ListPage";
export { ${entityName}CreatePage } from "./${entityName}CreatePage";
export { ${entityName}EditPage } from "./${entityName}EditPage";
`;
}

/**
 * Generates services index file with all exports
 */
function generateServicesIndex(entityLower: string): string {
  return `/**
 * Services
 * Auto-generated by Low-Code Builder
 */

export * from "./${entityLower}Service";
`;
}

/**
 * Generates feature index file with all exports
 */
function generateFeatureIndex(entityName: string): string {
  return `/**
 * ${entityName} Feature
 * Auto-generated by Low-Code Builder
 */

export * from "./types";
export * from "./components";
export * from "./pages";
export * from "./services";
`;
}

/**
 * Generates types index file
 */
function generateTypesIndex(entityLower: string): string {
  return `/**
 * Types
 * Auto-generated by Low-Code Builder
 */

export * from "./${entityLower}";
`;
}

/**
 * Generates all files for a feature
 * Creates complete folder structure with types, components, pages, services
 *
 * Requirements: 4.1, 4.2, 4.3, 4.4, 4.5
 */
export function generateFeatureFiles(
  entity: EntityDefinition,
): GeneratedFile[] {
  if (!entity.name || entity.fields.length === 0) {
    return [];
  }

  const entityName = entity.name;
  const entityLower = toLowerCamelCase(entityName);
  const basePath = `src/features/${entityLower}`;

  const files: GeneratedFile[] = [
    // Types
    {
      path: `${basePath}/types/${entityLower}.ts`,
      content: generateTypesFile(entity),
    },
    {
      path: `${basePath}/types/index.ts`,
      content: generateTypesIndex(entityLower),
    },

    // Components
    {
      path: `${basePath}/components/${entityName}Form.tsx`,
      content: generateFormComponent(entity),
    },
    {
      path: `${basePath}/components/${entityName}Card.tsx`,
      content: generateCardComponent(entity),
    },
    {
      path: `${basePath}/components/${entityName}List.tsx`,
      content: generateListComponent(entity),
    },
    {
      path: `${basePath}/components/index.ts`,
      content: generateComponentsIndex(entityName),
    },

    // Pages
    {
      path: `${basePath}/pages/${entityName}ListPage.tsx`,
      content: generateListPage(entity),
    },
    {
      path: `${basePath}/pages/${entityName}CreatePage.tsx`,
      content: generateCreatePage(entity),
    },
    {
      path: `${basePath}/pages/${entityName}EditPage.tsx`,
      content: generateEditPage(entity),
    },
    {
      path: `${basePath}/pages/index.ts`,
      content: generatePagesIndex(entityName),
    },

    // Services
    {
      path: `${basePath}/services/${entityLower}Service.ts`,
      content: generateService(entity),
    },
    {
      path: `${basePath}/services/index.ts`,
      content: generateServicesIndex(entityLower),
    },

    // Feature index
    {
      path: `${basePath}/index.ts`,
      content: generateFeatureIndex(entityName),
    },
  ];

  return files;
}

/**
 * Generates route configuration code for main.tsx
 * Includes list, create, and edit routes
 *
 * Requirements: 6.1, 6.2
 */
export function generateRouteConfig(entity: EntityDefinition): string {
  if (!entity.name || entity.fields.length === 0) {
    return `// Empty entity - no routes generated`;
  }

  const entityName = entity.name;
  const entityLower = toLowerCamelCase(entityName);

  return `// Add these imports to main.tsx
import {
  ${entityName}ListPage,
  ${entityName}CreatePage,
  ${entityName}EditPage,
} from "./features/${entityLower}";

// Add these routes to your router configuration
<Route path="/${entityLower}s" element={<${entityName}ListPage />} />
<Route path="/${entityLower}s/new" element={<${entityName}CreatePage />} />
<Route path="/${entityLower}s/:id/edit" element={<${entityName}EditPage />} />
`;
}

/**
 * Exports feature to file system (browser download)
 * Creates a downloadable zip file or shows copy dialog
 *
 * Requirements: 4.6, 4.7
 */
export async function exportFeature(
  entity: EntityDefinition,
): Promise<ExportResult> {
  try {
    const files = generateFeatureFiles(entity);

    if (files.length === 0) {
      return {
        success: false,
        files: [],
        error:
          "No files generated. Entity must have a name and at least one field.",
      };
    }

    // In browser environment, we'll return the files for UI to handle
    // The UI can then use File System Access API or download as zip
    return {
      success: true,
      files: files.map((f) => f.path),
    };
  } catch (error) {
    return {
      success: false,
      files: [],
      error: error instanceof Error ? error.message : "Unknown error occurred",
    };
  }
}
